# Jenkins CI/CD Stack for Local Development
version: '3.8'

services:
  # Jenkins Master
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: sentinelhub-jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    networks:
      - jenkins-network

  # Jenkins Agent (for distributed builds)
  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: sentinelhub-jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent-1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - jenkins_agent_home:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
    networks:
      - jenkins-network

  # SonarQube for Code Quality
  sonarqube:
    image: sonarqube:community
    container_name: sentinelhub-jenkins-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - sonar-db
    networks:
      - jenkins-network

  # PostgreSQL for SonarQube
  sonar-db:
    image: postgres:13
    container_name: sentinelhub-jenkins-postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_postgres_data:/var/lib/postgresql/data
    networks:
      - jenkins-network

  # Nexus Repository (Optional - for artifact management)
  nexus:
    image: sonatype/nexus3:latest
    container_name: sentinelhub-nexus
    ports:
      - "8081:8081"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=273m
    volumes:
      - nexus_data:/nexus-data
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  jenkins_agent_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_postgres_data:
  nexus_data:

networks:
  jenkins-network:
    driver: bridge
