# Prometheus configuration for SentinelHub monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "sentinelhub_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # SentinelHub API Gateway metrics
  - job_name: 'sentinelhub-api'
    static_configs:
      - targets: ['api-gateway:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node.js application metrics
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['api-gateway:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s

  # Docker container metrics (if docker metrics enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s

  # SonarQube metrics
  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Storage retention
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB